'use strict';function x(e,a,b,c,g){e.u.xc(e.cb,a,b,c,g)}function B(e,a,b,c){e.u.ea?x(e,a,b,c):e.u.qf()._OnMessageFromDOM({type:"event",component:e.cb,handler:a,dispatchOpts:c||null,data:b,responseId:null})}function E(e,a,b){e.u.C(e.cb,a,b)}function I(e,a){for(const [b,c]of a)E(e,b,c)}function J(e){e.Ub||(e.u.$e(e.ke),e.Ub=!0)}function L(e){e.Ub&&(e.u.mg(e.ke),e.Ub=!1)}window.zb=class{constructor(e,a){this.u=e;this.cb=a;this.Ub=!1;this.ke=()=>this.wa()}md(){}wa(){}};
function M(e){-1!==e.Ra&&(self.clearTimeout(e.Ra),e.Ra=-1)}window.Re=class{constructor(e,a){this.Sc=e;this.Ng=a;this.Ra=-1;this.Wb=-Infinity;this.le=()=>{this.Ra=-1;this.Wb=Date.now();this.ib=!0;this.Sc();this.ib=!1};this.Ud=this.ib=!1}f(){M(this);this.le=this.Sc=null}};"use strict";
function N(e,a){const b=a.elementId,c=e.pc(b,a);e.V.set(b,c);c.style.boxSizing="border-box";a.isVisible||(c.style.display="none");c.addEventListener("focus",()=>{P(e,"elem-focused",b)});c.addEventListener("blur",()=>{P(e,"elem-blurred",b)});e.bb&&document.body.appendChild(c)}function Q(e,a,b){E(e,a,c=>{const g=e.V.get(c.elementId);return b(g,c)})}function P(e,a,b,c){c||(c={});c.elementId=b;x(e,a,c)}
window.qd=class extends self.zb{constructor(e,a){super(e,a);this.V=new Map;this.bb=!0;I(this,[["create",b=>N(this,b)],["destroy",b=>{{b=b.elementId;const c=this.V.get(b);this.sd(c);this.bb&&c.parentElement.removeChild(c);this.V.delete(b)}}],["set-visible",b=>{this.bb&&(this.V.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.bb){var c=this.V.get(b.elementId);c.style.left=b.left+"px";c.style.top=b.top+"px";c.style.width=b.width+"px";c.style.height=b.height+"px";
b=b.fontSize;null!==b&&(c.style.fontSize=b+"em")}}],["update-state",b=>{{const c=this.V.get(b.elementId);this.Hb(c,b)}}],["focus",b=>{{const c=this.V.get(b.elementId);b.focus?c.focus():c.blur()}}],["set-css-style",b=>{this.V.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.V.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.V.get(b.elementId).removeAttribute(b.name)}]]);Q(this,"get-element",b=>b)}pc(){throw Error("required override");}sd(){}Hb(){throw Error("required override");
}};"use strict";
{const e=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let a=0;function b(h){const d=document.createElement("script");d.async=!1;d.type="module";return h.Zg?new Promise(k=>{const l="c3_resolve_"+a;++a;self[l]=k;d.textContent=h.dh+`\n\nself["${l}"]();`;document.head.appendChild(d)}):new Promise((k,l)=>{d.onload=k;d.onerror=l;d.src=h;document.head.appendChild(d)})}let c=!1,g=!1;function m(){if(!c){try{new Worker("blob://",{get type(){g=!0}})}catch(h){}c=!0}return g}let p=
new Audio;const u={"audio/webm; codecs=opus":!!p.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!p.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!p.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!p.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!p.canPlayType("audio/mp4"),"audio/mpeg":!!p.canPlayType("audio/mpeg")};p=null;async function A(h){h=await C(h);return(new TextDecoder("utf-8")).decode(h)}function C(h){return new Promise((d,
k)=>{const l=new FileReader;l.onload=n=>d(n.target.result);l.onerror=n=>k(n);l.readAsArrayBuffer(h)})}const v=[];let w=0;window.RealFile=window.File;const D=[],H=new Map,z=new Map;let K=0;const F=[];self.runOnStartup=function(h){if("function"!==typeof h)throw Error("runOnStartup called without a function");F.push(h)};const O=new Set(["cordova","playable-ad","instant-games"]);let f=!1;window.Ea=class h{constructor(d){this.ea=d.fh;this.ra=null;this.F="";this.jc=d.bh;this.xb={};this.Ka=this.wb=null;
this.Sb=[];this.lb=this.G=this.Pa=null;this.Oa=-1;this.Sg=()=>this.Sf();this.Na=[];this.A=d.me;this.jb="file"===location.protocol.substr(0,4);!this.ea||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&m()||(this.ea=!1);if("playable-ad"===this.A||"instant-games"===this.A)this.ea=!1;if("cordova"===this.A&&this.ea)if(/android/i.test(navigator.userAgent)){const k=/Chrome\/(\d+)/i.exec(navigator.userAgent);k&&90<=parseInt(k[1],10)||(this.ea=!1)}else this.ea=!1;this.Yb=this.ja=null;"html5"!==
this.A&&"playable-ad"!==this.A||!this.jb||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");"html5"!==this.A||window.isSecureContext||console.warn("[Construct 3] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.C("runtime","cordova-fetch-local-file",k=>this.zf(k));this.C("runtime",
"create-job-worker",()=>this.Af());"cordova"===this.A?document.addEventListener("deviceready",()=>this.Fd(d)):this.Fd(d)}f(){this.Dc();this.ra&&(this.ra=this.ra.onmessage=null);this.wb&&(this.wb.terminate(),this.wb=null);this.Ka&&(this.Ka.f(),this.Ka=null);this.G&&(this.G.parentElement.removeChild(this.G),this.G=null)}Me(){return e&&"cordova"===this.A}wc(){const d=navigator.userAgent;return e&&O.has(this.A)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(d)}async Fd(d){"macos-wkwebview"===
this.A&&this.pg();if("playable-ad"===this.A){this.ja=self.c3_base64files;this.Yb={};await this.ef();for(let l=0,n=d.Sa.length;l<n;++l){var k=d.Sa[l].toLowerCase();this.Yb.hasOwnProperty(k)?d.Sa[l]={Zg:!0,dh:this.Yb[k]}:this.ja.hasOwnProperty(k)&&(d.Sa[l]=URL.createObjectURL(this.ja[k]))}}d.Ug?this.F=d.Ug:(k=location.origin,this.F=("null"===k?"file:///":k)+location.pathname,k=this.F.lastIndexOf("/"),-1!==k&&(this.F=this.F.substr(0,k+1)));d.hh&&(this.xb=d.hh);k=new MessageChannel;this.ra=k.port1;this.ra.onmessage=
l=>this._OnMessageFromRuntime(l.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(l=>this.Mf(l));this.lb=new self.Ne(this);await R(this.lb);"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.ea?await this.tf(d,k.port2):await this.sf(d,k.port2)}Gc(d){d=this.xb.hasOwnProperty(d)?this.xb[d]:d.endsWith("/workermain.js")&&this.xb.hasOwnProperty("workermain.js")?this.xb["workermain.js"]:
"playable-ad"===this.A&&this.ja.hasOwnProperty(d.toLowerCase())?this.ja[d.toLowerCase()]:d;d instanceof Blob&&(d=URL.createObjectURL(d));return d}async qc(d,k,l){if(d.startsWith("blob:"))return new Worker(d,l);if("cordova"===this.A&&this.jb)return d=await this.yb(l.Yg?d:this.jc+d),new Worker(URL.createObjectURL(new Blob([d],{type:"application/javascript"})),l);d=new URL(d,k);if(location.origin!==d.origin){d=await fetch(d);if(!d.ok)throw Error("failed to fetch worker script");d=await d.blob();return new Worker(URL.createObjectURL(d),
l)}return new Worker(d,l)}ya(){return Math.max(window.innerWidth,1)}xa(){return Math.max(window.innerHeight,1)}Ed(d){var k=this.lb;return{baseUrl:this.F,windowInnerWidth:this.ya(),windowInnerHeight:this.xa(),devicePixelRatio:window.devicePixelRatio,isFullscreen:h.Wa(),projectData:d.mh,previewImageBlobs:window.cr_previewImageBlobs||this.ja,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,swClientId:window.kh||"",exportType:d.me,isDebug:-1<
self.location.search.indexOf("debug"),ife:!!self.lh,jobScheduler:{inputPort:k.Zc,outputPort:k.ed,maxNumWorkers:k.Pg},supportedAudioFormats:u,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.jc+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.jc+"opus.wasm.wasm",isFileProtocol:this.jb,isiOSCordova:this.Me(),isiOSWebView:this.wc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async tf(d,k){var l=this.Gc(d.gh);this.wb=await this.qc(l,this.F,{type:"module",name:"Runtime",
Yg:!0});this.G=document.createElement("canvas");this.G.style.display="none";l=this.G.transferControlToOffscreen();document.body.appendChild(this.G);window.c3canvas=this.G;let n=d.ld||[],t=d.Sa;n=await Promise.all(n.map(q=>this.Fa(q)));t=await Promise.all(t.map(q=>this.Fa(q)));if("cordova"===this.A)for(let q=0,r=d.nc.length;q<r;++q){const y=d.nc[q],G=y[0];if(G===d.jd||"scriptsInEvents.js"===G||G.endsWith("/scriptsInEvents.js"))y[1]=await this.Fa(G)}this.wb.postMessage(Object.assign(this.Ed(d),{type:"init-runtime",
isInWorker:!0,messagePort:k,canvas:l,workerDependencyScripts:n,engineScripts:t,projectScripts:d.nc,mainProjectScript:d.jd,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[k,l,...S(this.lb)]);this.Sb=D.map(q=>new q(this));this.Dd();self.c3_callFunction=(q,r)=>this.Pa.uf(q,r);"preview"===this.A&&(self.goToLastErrorScript=()=>this.xc("runtime","go-to-last-error-script"))}async sf(d,k){this.G=document.createElement("canvas");this.G.style.display="none";document.body.appendChild(this.G);window.c3canvas=
this.G;this.Sb=D.map(q=>new q(this));this.Dd();var l=d.Sa.map(q=>"string"===typeof q?(new URL(q,this.F)).toString():q);Array.isArray(d.ld)&&l.unshift(...d.ld);l=await Promise.all(l.map(q=>this.Fa(q)));await Promise.all(l.map(q=>b(q)));l=self.C3_ProjectScriptsStatus;const n=d.jd,t=d.nc;for(let [q,r]of t)if(r||(r=q),q===n)try{r=await this.Fa(r),await b(r),"preview"!==this.A||l[q]||this.Od(q,"main script did not run to completion")}catch(y){this.Od(q,y)}else if("scriptsInEvents.js"===q||q.endsWith("/scriptsInEvents.js"))r=
await this.Fa(r),await b(r);"preview"===this.A&&"object"!==typeof self.ih.jh?(this.Mb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(d=Object.assign(this.Ed(d),{isInWorker:!1,messagePort:k,canvas:this.G,runOnStartupFunctions:F}),this.Hd(),this.Ka=self.C3_CreateRuntime(d),await self.C3_InitRuntime(this.Ka,d))}Od(d,
k){this.Mb();console.error(`[Preview] Failed to load project main script (${d}): `,k);alert(`Failed to load project main script (${d}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Hd(){this.Mb()}Mb(){const d=window.Vg;d&&(d.parentElement.removeChild(d),window.Vg=null)}async Af(){const d=await T(this.lb);return{outputPort:d,transferables:[d]}}qf(){if(this.ea)throw Error("not available in worker mode");return this.Ka}xc(d,k,l,n,t){this.ra.postMessage({type:"event",
component:d,handler:k,dispatchOpts:n||null,data:l,responseId:null},t)}wd(d,k,l,n,t){const q=K++,r=new Promise((y,G)=>{z.set(q,{resolve:y,reject:G})});this.ra.postMessage({type:"event",component:d,handler:k,dispatchOpts:n||null,data:l,responseId:q},t);return r}["_OnMessageFromRuntime"](d){const k=d.type;if("event"===k)return this.Ff(d);if("result"===k)this.Vf(d);else if("runtime-ready"===k)this.Wf();else if("alert-error"===k)this.Mb(),alert(d.message);else if("creating-runtime"===k)this.Hd();else throw Error(`unknown message '${k}'`);
}Ff(d){const k=d.component,l=d.handler,n=d.data,t=d.responseId;if(d=H.get(k))if(d=d.get(l)){var q=null;try{q=d(n)}catch(r){console.error(`Exception in '${k}' handler '${l}':`,r);null!==t&&this.Lb(t,!1,""+r);return}if(null===t)return q;q&&q.then?q.then(r=>this.Lb(t,!0,r)).catch(r=>{console.error(`Rejection from '${k}' handler '${l}':`,r);this.Lb(t,!1,""+r)}):this.Lb(t,!0,q)}else console.warn(`[DOM] No handler '${l}' for component '${k}'`);else console.warn(`[DOM] No event handlers for component '${k}'`)}Lb(d,
k,l){let n;l&&l.transferables&&(n=l.transferables);this.ra.postMessage({type:"result",responseId:d,isOk:k,result:l},n)}Vf(d){const k=d.responseId,l=d.isOk;d=d.result;const n=z.get(k);l?n.resolve(d):n.reject(d);z.delete(k)}C(d,k,l){let n=H.get(d);n||(n=new Map,H.set(d,n));if(n.has(k))throw Error(`[DOM] Component '${d}' already has handler '${k}'`);n.set(k,l)}static Ta(d){if(D.includes(d))throw Error("DOM handler already added");D.push(d)}Dd(){for(const d of this.Sb)if("runtime"===d.cb){this.Pa=d;return}throw Error("cannot find runtime DOM handler");
}Mf(d){this.xc("debugger","message",d)}Wf(){for(const d of this.Sb)d.md()}static Wa(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||f)}static Pd(d){f=!!d}$e(d){this.Na.push(d);this.Qc()}mg(d){d=this.Na.indexOf(d);if(-1===d)throw Error("invalid callback");this.Na.splice(d,1);this.Na.length||this.Dc()}Qc(){-1===this.Oa&&this.Na.length&&(this.Oa=requestAnimationFrame(this.Sg))}Dc(){-1!==this.Oa&&(cancelAnimationFrame(this.Oa),this.Oa=-1)}Sf(){this.Oa=
-1;for(const d of this.Na)d();this.Qc()}Z(d){this.Pa.Z(d)}aa(d){this.Pa.aa(d)}Pc(){this.Pa.Pc()}Fb(d){this.Pa.Fb(d)}Le(){return!!u["audio/webm; codecs=opus"]}async Lg(d){d=await this.wd("runtime","opus-decode",{arrayBuffer:d},null,[d]);return new Float32Array(d)}Ke(d){return/^(?:[a-z\-]+:)?\/\//.test(d)||"data:"===d.substr(0,5)||"blob:"===d.substr(0,5)}vd(d){return!this.Ke(d)}async Fa(d){return"cordova"===this.A&&(d.startsWith("file:")||this.jb&&this.vd(d))?(d.startsWith(this.F)&&(d=d.substr(this.F.length)),
d=await this.yb(d),URL.createObjectURL(new Blob([d],{type:"application/javascript"}))):d}async zf(d){const k=d.filename;switch(d.as){case "text":return await this.De(k);case "buffer":return await this.yb(k);default:throw Error("unsupported type");}}pd(d){const k=window.cordova.file.applicationDirectory+"www/"+d.toLowerCase();return new Promise((l,n)=>{window.resolveLocalFileSystemURL(k,t=>{t.file(l,n)},n)})}async De(d){d=await this.pd(d);return await A(d)}Ec(){if(v.length&&!(8<=w)){w++;var d=v.shift();
this.ff(d.filename,d.eh,d.Xg)}}yb(d){return new Promise((k,l)=>{v.push({filename:d,eh:n=>{w--;this.Ec();k(n)},Xg:n=>{w--;this.Ec();l(n)}});this.Ec()})}async ff(d,k,l){try{const n=await this.pd(d),t=await C(n);k(t)}catch(n){l(n)}}pg(){var d={type:"ready"};if("windows-webview2"===this.A)window.chrome.webview.postMessage(JSON.stringify(d));else if("macos-wkwebview"===this.A)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(d));else throw Error("cannot send wrapper message");}async ef(){const d=
[];for(const [k,l]of Object.entries(this.ja))d.push(this.df(k,l));await Promise.all(d)}async df(d,k){if("object"===typeof k)this.ja[d]=new Blob([k.str],{type:k.type}),this.Yb[d]=k.str;else{let l=await this.nf(k);l||(l=this.hf(k));this.ja[d]=l}}async nf(d){try{return await (await fetch(d)).blob()}catch(k){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
k),null}}hf(d){d=this.gg(d);return this.cf(d.data,d.$g)}gg(d){var k=d.indexOf(",");if(0>k)throw new URIError("expected comma in data: uri");var l=d.substring(k+1);k=d.substring(5,k).split(";");d=k[0]||"";const n=k[2];l="base64"===k[1]||"base64"===n?atob(l):decodeURIComponent(l);return{$g:d,data:l}}cf(d,k){var l=d.length;let n=l>>2,t=new Uint8Array(l),q=new Uint32Array(t.buffer,0,n),r,y;for(y=r=0;r<n;++r)q[r]=d.charCodeAt(y++)|d.charCodeAt(y++)<<8|d.charCodeAt(y++)<<16|d.charCodeAt(y++)<<24;for(l&=
3;l--;)t[y]=d.charCodeAt(y),++y;return new Blob([t],{type:k})}}}"use strict";
{const e=self.Ea;function a(f){return f.sourceCapabilities&&f.sourceCapabilities.firesTouchEvents||f.originalEvent&&f.originalEvent.sourceCapabilities&&f.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),c={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},g={dispatchUserScriptEvent:!0},m={dispatchRuntimeEvent:!0};function p(f){return new Promise((h,d)=>{const k=document.createElement("link");k.onload=()=>h(k);k.onerror=l=>d(l);k.rel=
"stylesheet";k.href=f;document.head.appendChild(k)})}function u(f){return new Promise((h,d)=>{const k=new Image;k.onload=()=>h(k);k.onerror=l=>d(l);k.src=f})}async function A(f){f=URL.createObjectURL(f);try{return await u(f)}finally{URL.revokeObjectURL(f)}}function C(f){return new Promise((h,d)=>{let k=new FileReader;k.onload=l=>h(l.target.result);k.onerror=l=>d(l);k.readAsText(f)})}async function v(f,h,d){if(!/firefox/i.test(navigator.userAgent))return await A(f);var k=await C(f);k=(new DOMParser).parseFromString(k,
"image/svg+xml");const l=k.documentElement;if(l.hasAttribute("width")&&l.hasAttribute("height")){const n=l.getAttribute("width"),t=l.getAttribute("height");if(!n.includes("%")&&!t.includes("%"))return await A(f)}l.setAttribute("width",h+"px");l.setAttribute("height",d+"px");k=(new XMLSerializer).serializeToString(k);f=new Blob([k],{type:"image/svg+xml"});return await A(f)}function w(f){do{if(f.parentNode&&f.hasAttribute("contenteditable"))return!0;f=f.parentNode}while(f);return!1}const D=new Set(["input",
"textarea","datalist","select"]),H=new Set(["canvas","body","html"]);function z(f){H.has(f.target.tagName.toLowerCase())&&f.preventDefault()}function K(f){(f.metaKey||f.ctrlKey)&&f.preventDefault()}self.C3_GetSvgImageSize=async function(f){f=await A(f);if(0<f.width&&0<f.height)return[f.width,f.height];{f.style.position="absolute";f.style.left="0px";f.style.top="0px";f.style.visibility="hidden";document.body.appendChild(f);const h=f.getBoundingClientRect();document.body.removeChild(f);return[h.width,
h.height]}};self.C3_RasterSvgImageBlob=async function(f,h,d,k,l){f=await v(f,h,d);const n=document.createElement("canvas");n.width=k;n.height=l;n.getContext("2d").drawImage(f,0,0,h,d);return n};let F=!1;document.addEventListener("pause",()=>F=!0);document.addEventListener("resume",()=>F=!1);function O(){try{return window.parent&&window.parent.document.hasFocus()}catch(f){return!1}}e.Ta(class extends self.zb{constructor(f){super(f,"runtime");this.Zd=!0;this.Qa=-1;this.gd="any";this.Qd=this.Rd=!1;this.Ja=
this.tb=this.Aa=null;this.ec=this.dc=0;f.C("canvas","update-size",k=>this.dg(k));f.C("runtime","invoke-download",k=>this.Kf(k));f.C("runtime","raster-svg-image",k=>this.Tf(k));f.C("runtime","get-svg-image-size",k=>this.Hf(k));f.C("runtime","set-target-orientation",k=>this.ag(k));f.C("runtime","register-sw",()=>this.Uf());f.C("runtime","post-to-debugger",k=>this.Jd(k));f.C("runtime","go-to-script",k=>this.Jd(k));f.C("runtime","before-start-ticking",()=>this.yf());f.C("runtime","debug-highlight",k=>
this.Bf(k));f.C("runtime","enable-device-orientation",()=>this.bf());f.C("runtime","enable-device-motion",()=>this.af());f.C("runtime","add-stylesheet",k=>this.wf(k));f.C("runtime","alert",k=>this.xf(k));f.C("runtime","hide-cordova-splash",()=>this.If());const h=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",k=>{const l=k.target;h.has(l.tagName.toLowerCase())||w(l)||k.preventDefault()});const d=f.G;window.addEventListener("selectstart",z);window.addEventListener("gesturehold",
z);d.addEventListener("selectstart",z);d.addEventListener("gesturehold",z);window.addEventListener("touchstart",z,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",z,{passive:!1}),d.addEventListener("pointerdown",z)):d.addEventListener("touchstart",z);this.qb=0;window.addEventListener("mousedown",k=>{1===k.button&&k.preventDefault()});window.addEventListener("mousewheel",K,{passive:!1});window.addEventListener("wheel",K,{passive:!1});window.addEventListener("resize",
()=>this.eg());window.addEventListener("fullscreenchange",()=>this.Ya());window.addEventListener("webkitfullscreenchange",()=>this.Ya());window.addEventListener("mozfullscreenchange",()=>this.Ya());window.addEventListener("fullscreenerror",k=>this.Lc(k));window.addEventListener("webkitfullscreenerror",k=>this.Lc(k));window.addEventListener("mozfullscreenerror",k=>this.Lc(k));f.wc()&&window.addEventListener("focusout",()=>{{const n=document.activeElement;if(n){var k=n.tagName.toLowerCase();var l=new Set("email number password search tel text url".split(" "));
k="textarea"===k?!0:"input"===k?l.has(n.type.toLowerCase()||"text"):w(n)}else k=!1}k||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=k=>this.fg(k);this.La=new Set;this.Zb=new WeakSet;this.qa=!1}yf(){"cordova"===this.u.A?(document.addEventListener("pause",()=>this.Oc(!0)),document.addEventListener("resume",()=>this.Oc(!1))):document.addEventListener("visibilitychange",()=>this.Oc(document.hidden));return{isSuspended:!(!document.hidden&&!F)}}md(){window.addEventListener("focus",()=>
this.$a("window-focus"));window.addEventListener("blur",()=>{this.$a("window-blur",{parentHasFocus:O()});this.qb=0});window.addEventListener("focusin",h=>{h=h.target;(D.has(h.tagName.toLowerCase())||w(h))&&this.$a("keyboard-blur")});window.addEventListener("keydown",h=>this.Id("keydown",h));window.addEventListener("keyup",h=>this.Id("keyup",h));window.addEventListener("dblclick",h=>this.Mc("dblclick",h,c));window.addEventListener("wheel",h=>this.Of(h));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
h=>{this.Hc(h);this.Za("pointerdown",h)}),this.u.ea&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.tb=new self.Re(()=>this.lf(),5),this.tb.Ud=!0,window.addEventListener("pointerrawupdate",h=>this.Rf(h))):window.addEventListener("pointermove",h=>this.Za("pointermove",h)),window.addEventListener("pointerup",h=>this.Za("pointerup",h)),window.addEventListener("pointercancel",h=>this.Za("pointercancel",h))):(window.addEventListener("mousedown",h=>{this.Hc(h);this.Nc("pointerdown",
h)}),window.addEventListener("mousemove",h=>this.Nc("pointermove",h)),window.addEventListener("mouseup",h=>this.Nc("pointerup",h)),window.addEventListener("touchstart",h=>{this.Hc(h);this.Kb("pointerdown",h)}),window.addEventListener("touchmove",h=>this.Kb("pointermove",h)),window.addEventListener("touchend",h=>this.Kb("pointerup",h)),window.addEventListener("touchcancel",h=>this.Kb("pointercancel",h)));const f=()=>this.Pc();window.addEventListener("pointerup",f,!0);window.addEventListener("touchend",
f,!0);window.addEventListener("click",f,!0);window.addEventListener("keydown",f,!0);window.addEventListener("gamepadconnected",f,!0)}$a(f,h){x(this,f,h||null,m)}ya(){return this.u.ya()}xa(){return this.u.xa()}eg(){const f=this.ya(),h=this.xa();this.$a("window-resize",{innerWidth:f,innerHeight:h,devicePixelRatio:window.devicePixelRatio,isFullscreen:e.Wa()});this.u.wc()&&(-1!==this.Qa&&clearTimeout(this.Qa),this.Kd(f,h,0))}ng(f,h,d){-1!==this.Qa&&clearTimeout(this.Qa);this.Qa=setTimeout(()=>this.Kd(f,
h,d),48)}Kd(f,h,d){const k=this.ya(),l=this.xa();this.Qa=-1;k!=f||l!=h?this.$a("window-resize",{innerWidth:k,innerHeight:l,devicePixelRatio:window.devicePixelRatio,isFullscreen:e.Wa()}):10>d&&this.ng(k,l,d+1)}ag(f){this.gd=f.targetOrientation}Hg(){const f=this.gd;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(f).catch(h=>console.warn("[Construct 3] Failed to lock orientation: ",h));else try{let h=!1;screen.lockOrientation?h=screen.lockOrientation(f):screen.webkitLockOrientation?
h=screen.webkitLockOrientation(f):screen.mozLockOrientation?h=screen.mozLockOrientation(f):screen.msLockOrientation&&(h=screen.msLockOrientation(f));h||console.warn("[Construct 3] Failed to lock orientation")}catch(h){console.warn("[Construct 3] Failed to lock orientation: ",h)}}Ya(){const f=e.Wa();f&&"any"!==this.gd&&this.Hg();x(this,"fullscreenchange",{isFullscreen:f,innerWidth:this.ya(),innerHeight:this.xa()})}Lc(f){console.warn("[Construct 3] Fullscreen request failed: ",f);x(this,"fullscreenerror",
{isFullscreen:e.Wa(),innerWidth:this.ya(),innerHeight:this.xa()})}Oc(f){f?this.u.Dc():this.u.Qc();x(this,"visibilitychange",{hidden:f})}Id(f,h){"Backspace"===h.key&&z(h);const d=b.get(h.code)||h.code;B(this,f,{code:d,key:h.key,which:h.which,repeat:h.repeat,altKey:h.altKey,ctrlKey:h.ctrlKey,metaKey:h.metaKey,shiftKey:h.shiftKey,timeStamp:h.timeStamp},c)}Of(f){x(this,"wheel",{clientX:f.clientX,clientY:f.clientY,pageX:f.pageX,pageY:f.pageY,deltaX:f.deltaX,deltaY:f.deltaY,deltaZ:f.deltaZ,deltaMode:f.deltaMode,
timeStamp:f.timeStamp},c)}Mc(f,h,d){a(h)||B(this,f,{button:h.button,buttons:h.buttons,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,movementX:h.movementX||0,movementY:h.movementY||0,timeStamp:h.timeStamp},d)}Nc(f,h){if(!a(h)){var d=this.qb;"pointerdown"===f&&0!==d?f="pointermove":"pointerup"===f&&0!==h.buttons&&(f="pointermove");B(this,f,{pointerId:1,pointerType:"mouse",button:h.button,buttons:h.buttons,lastButtons:d,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,
movementX:h.movementX||0,movementY:h.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:h.timeStamp},c);this.qb=h.buttons;this.Mc(h.type,h,g)}}Za(f,h){if(this.tb&&"pointermove"!==f){var d=this.tb;d.ib||(M(d),d.Wb=Date.now())}d=0;"mouse"===h.pointerType&&(d=this.qb);B(this,f,{pointerId:h.pointerId,pointerType:h.pointerType,button:h.button,buttons:h.buttons,lastButtons:d,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,movementX:(h.movementX||
0)+this.dc,movementY:(h.movementY||0)+this.ec,width:h.width||0,height:h.height||0,pressure:h.pressure||0,tangentialPressure:h.tangentialPressure||0,tiltX:h.tiltX||0,tiltY:h.tiltY||0,twist:h.twist||0,timeStamp:h.timeStamp},c);this.ec=this.dc=0;"mouse"===h.pointerType&&(d="mousemove","pointerdown"===f?d="mousedown":"pointerup"===f&&(d="mouseup"),this.Mc(d,h,g),this.qb=h.buttons)}Rf(f){this.Ja&&(this.dc+=this.Ja.movementX||0,this.ec+=this.Ja.movementY||0);this.Ja=f;f=this.tb;if(-1===f.Ra){var h=Date.now(),
d=h-f.Wb,k=f.Ng;d>=k&&f.Ud?(f.Wb=h,f.ib=!0,f.Sc(),f.ib=!1):f.Ra=self.setTimeout(f.le,Math.max(k-d,4))}}lf(){this.Za("pointermove",this.Ja);this.Ja=null}Kb(f,h){for(let d=0,k=h.changedTouches.length;d<k;++d){const l=h.changedTouches[d];B(this,f,{pointerId:l.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:l.clientX,clientY:l.clientY,pageX:l.pageX,pageY:l.pageY,movementX:h.movementX||0,movementY:h.movementY||0,width:2*(l.radiusX||l.webkitRadiusX||0),height:2*(l.radiusY||l.webkitRadiusY||
0),pressure:l.force||l.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:l.rotationAngle||0,timeStamp:h.timeStamp},c)}}Hc(f){window!==window.top&&window.focus();this.Gd(f.target)&&document.activeElement&&!this.Gd(document.activeElement)&&document.activeElement.blur()}Gd(f){return!f||f===document||f===window||f===document.body||"canvas"===f.tagName.toLowerCase()}bf(){this.Rd||(this.Rd=!0,window.addEventListener("deviceorientation",f=>this.Df(f)),window.addEventListener("deviceorientationabsolute",
f=>this.Ef(f)))}af(){this.Qd||(this.Qd=!0,window.addEventListener("devicemotion",f=>this.Cf(f)))}Df(f){x(this,"deviceorientation",{absolute:!!f.absolute,alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0,timeStamp:f.timeStamp,webkitCompassHeading:f.webkitCompassHeading,webkitCompassAccuracy:f.webkitCompassAccuracy},c)}Ef(f){x(this,"deviceorientationabsolute",{absolute:!!f.absolute,alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0,timeStamp:f.timeStamp},c)}Cf(f){let h=null;var d=f.acceleration;d&&(h=
{x:d.x||0,y:d.y||0,z:d.z||0});d=null;var k=f.accelerationIncludingGravity;k&&(d={x:k.x||0,y:k.y||0,z:k.z||0});k=null;const l=f.rotationRate;l&&(k={alpha:l.alpha||0,beta:l.beta||0,gamma:l.gamma||0});x(this,"devicemotion",{acceleration:h,accelerationIncludingGravity:d,rotationRate:k,interval:f.interval,timeStamp:f.timeStamp},c)}dg(f){const h=this.u.G;h.style.width=f.styleWidth+"px";h.style.height=f.styleHeight+"px";h.style.marginLeft=f.marginLeft+"px";h.style.marginTop=f.marginTop+"px";this.Zd&&(h.style.display=
"",this.Zd=!1)}Kf(f){const h=f.url;f=f.filename;const d=document.createElement("a"),k=document.body;d.textContent=f;d.href=h;d.download=f;k.appendChild(d);d.click();k.removeChild(d)}async Tf(f){var h=f.imageBitmapOpts;f=await self.C3_RasterSvgImageBlob(f.blob,f.imageWidth,f.imageHeight,f.surfaceWidth,f.surfaceHeight);h=h?await createImageBitmap(f,h):await createImageBitmap(f);return{imageBitmap:h,transferables:[h]}}async Hf(f){return await self.C3_GetSvgImageSize(f.blob)}async wf(f){await p(f.url)}Pc(){var f=
[...this.La];this.La.clear();if(!this.qa)for(const h of f)(f=h.play())&&f.catch(()=>{this.Zb.has(h)||this.La.add(h)})}Z(f){if("function"!==typeof f.play)throw Error("missing play function");this.Zb.delete(f);let h;try{h=f.play()}catch(d){this.La.add(f);return}h&&h.catch(()=>{this.Zb.has(f)||this.La.add(f)})}aa(f){this.La.delete(f);this.Zb.add(f)}Fb(f){this.qa=!!f}If(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}Bf(f){if(f.show){this.Aa||(this.Aa=document.createElement("div"),
this.Aa.id="inspectOutline",document.body.appendChild(this.Aa));var h=this.Aa;h.style.display="";h.style.left=f.left-1+"px";h.style.top=f.top-1+"px";h.style.width=f.width+2+"px";h.style.height=f.height+2+"px";h.textContent=f.name}else this.Aa&&(this.Aa.style.display="none")}Uf(){window.C3_RegisterSW&&window.C3_RegisterSW()}Jd(f){window.c3_postToMessagePort&&(f.from="runtime",window.c3_postToMessagePort(f))}uf(f,h){return this.u.wd(this.cb,"js-invoke-function",{name:f,params:h},void 0,void 0)}xf(f){alert(f.message)}fg(f){"entered-fullscreen"===
f?(e.Pd(!0),this.Ya()):"exited-fullscreen"===f?(e.Pd(!1),this.Ya()):console.warn("Unknown wrapper message: ",f)}})}"use strict";async function R(e){if(e.Mg)throw Error("already initialised");e.Mg=!0;var a=e.ic.Gc("dispatchworker.js");e.Vc=await e.ic.qc(a,e.F,{name:"DispatchWorker"});a=new MessageChannel;e.Zc=a.port1;e.Vc.postMessage({type:"_init","in-port":a.port2},[a.port2]);e.ed=await T(e)}function S(e){return[e.Zc,e.ed]}
async function T(e){const a=e.$d.length;var b=e.ic.Gc("jobworker.js");b=await e.ic.qc(b,e.F,{name:"JobWorker"+a});const c=new MessageChannel,g=new MessageChannel;e.Vc.postMessage({type:"_addJobWorker",port:c.port1},[c.port1]);b.postMessage({type:"init",number:a,"dispatch-port":c.port2,"output-port":g.port2},[c.port2,g.port2]);e.$d.push(b);return g.port1}
self.Ne=class{constructor(e){this.ic=e;this.F=e.F;this.F="preview"===e.A?this.F+"workers/":this.F+e.jc;this.Pg=Math.min(navigator.hardwareConcurrency||2,16);this.Vc=null;this.$d=[];this.ed=this.Zc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.Ea({fh:!0,gh:"workermain.js",Sa:["scripts/c3runtime.js"],nc:[],jd:"",bh:"scripts/",ld:["box2d.wasm.js"],me:"html5"}));"use strict";
{const e=180/Math.PI;self.fa=class extends self.zb{constructor(a){super(a,"audio");this.Rb=this.c=null;this.Tb=this.Yc=!1;this.ta=()=>this.Ig();this.ca=[];this.D=[];this.ia=null;this.ae="";this.be=-1;this.sb=new Map;this.bd=1;this.qa=!1;this.hd=0;this.lc=1;this.Wc=0;this.de="HRTF";this.Vd="inverse";this.ee=600;this.ce=1E4;this.ge=1;this.Xd=this.fd=!1;this.je=this.u.Le();this.da=new Map;this.Ha=new Set;this.$c=!1;this.cd="";this.Ba=null;self.C3Audio_OnMicrophoneStream=(b,c)=>this.Nf(b,c);this.Qb=null;
self.C3Audio_GetOutputStream=()=>this.Gf();self.C3Audio_DOMInterface=this;I(this,[["create-audio-context",b=>this.gf(b)],["play",b=>this.hg(b)],["stop",b=>this.Fg(b)],["stop-all",()=>this.Gg()],["set-paused",b=>this.yg(b)],["set-volume",b=>this.Dg(b)],["fade-volume",b=>this.mf(b)],["set-master-volume",b=>this.wg(b)],["set-muted",b=>this.xg(b)],["set-silent",b=>this.Ag(b)],["set-looping",b=>this.vg(b)],["set-playback-rate",b=>this.zg(b)],["seek",b=>this.og(b)],["preload",b=>this.ig(b)],["unload",b=>
this.Jg(b)],["unload-all",()=>this.Kg()],["set-suspended",b=>this.Bg(b)],["get-suspended",()=>this.rf()],["add-effect",b=>this.Bd(b)],["set-effect-param",b=>this.sg(b)],["remove-effects",b=>this.kg(b)],["tick",b=>this.cg(b)],["load-state",b=>this.Lf(b)]])}async gf(a){a.isiOSCordova&&(this.fd=!0);this.hd=a.timeScaleMode;this.de=["equalpower","HRTF","soundfield"][a.panningModel];this.Vd=["linear","inverse","exponential"][a.distanceModel];this.ee=a.refDistance;this.ce=a.maxDistance;this.ge=a.rolloffFactor;
var b={latencyHint:a.latencyHint};this.je||(b.sampleRate=48E3);if("undefined"!==typeof AudioContext)this.c=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.c=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.Cd();this.c.onstatechange=()=>{"running"!==this.c.state&&this.Cd()};this.Rb=this.c.createGain();this.Rb.connect(this.c.destination);b=a.listenerPos;this.c.listener.setPosition(b[0],b[1],b[2]);this.c.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=
()=>this.rc();try{await Promise.all(a.preloadList.map(c=>this.Ib(c.originalUrl,c.url,c.type,!1)))}catch(c){console.error("[Construct 3] Preloading sounds failed: ",c)}return{sampleRate:this.c.sampleRate}}Cd(){this.Tb||(this.Yc=!1,window.addEventListener("pointerup",this.ta,!0),window.addEventListener("touchend",this.ta,!0),window.addEventListener("click",this.ta,!0),window.addEventListener("keydown",this.ta,!0),this.Tb=!0)}jf(){this.Tb&&(this.Yc=!0,window.removeEventListener("pointerup",this.ta,!0),
window.removeEventListener("touchend",this.ta,!0),window.removeEventListener("click",this.ta,!0),window.removeEventListener("keydown",this.ta,!0),this.Tb=!1)}Ig(){if(!this.Yc){var a=this.c;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),c=a.createBufferSource();c.buffer=b;c.connect(a.destination);c.start(0);"running"===a.state&&this.jf()}}X(){return this.c}rc(){return this.c.currentTime}ua(){return this.Rb}td(a){return(a=this.da.get(a.toLowerCase()))?a[0].P():this.ua()}ne(a,
b){a=a.toLowerCase();let c=this.da.get(a);c||(c=[],this.da.set(a,c));b.ug(c.length);b.Cg(a);c.push(b);this.Nd(a)}Nd(a){let b=this.ua();const c=this.da.get(a);if(c&&c.length){b=c[0].P();for(let g=0,m=c.length;g<m;++g){const p=c[g];g+1===m?p.S(this.ua()):p.S(c[g+1].P())}}for(const g of this.na(a))g.Se(b);this.Ba&&this.cd===a&&(this.Ba.disconnect(),this.Ba.connect(b))}Bb(){return this.bd}Cb(){return this.qa}tg(){this.Xd=!0}Fe(a,b){return b?this.u.Lg(a).then(c=>{const g=this.c.createBuffer(1,c.length,
48E3);g.getChannelData(0).set(c);return g}):new Promise((c,g)=>{this.c.decodeAudioData(a,c,g)})}Z(a){this.u.Z(a)}aa(a){this.u.aa(a)}xd(a){let b=0;for(let c=0,g=this.D.length;c<g;++c){const m=this.D[c];this.D[b]=m;m.L===a?m.f():++b}this.D.length=b}Te(){let a=0;for(let b=0,c=this.ca.length;b<c;++b){const g=this.ca[b];this.ca[a]=g;g.va()?g.f():++a}this.ca.length=a}*na(a){if(a)for(const b of this.D)self.fa.Ge(b.$,a)&&(yield b);else this.ia&&!this.ia.T()&&(yield this.ia)}async Ib(a,b,c,g,m){for(const p of this.ca)if(p.Va()===
b)return await U(p),p;if(m)return null;g&&(this.fd||this.Xd)&&this.Te();m="audio/webm; codecs=opus"===c&&!this.je;g&&m&&this.tg();a=!g||this.fd||m?new self.Be(this,a,b,c,g,m):new self.ze(this,a,b,c,g);this.ca.push(a);await U(a);return a}async Fc(a,b,c,g,m){for(const p of this.D)if(p.Va()===b&&(p.oc()||m))return p.Ve(g),p;a=await this.Ib(a,b,c,m);g="html5"===a.Rc?new self.Ae(a.i,a,g):new self.Ce(a.i,a,g);this.D.push(g);return g}Ze(a){let b=this.sb.get(a);if(!b){let c=null;b={kd:0,ah:new Promise(g=>
c=g),resolve:c};this.sb.set(a,b)}b.kd++}lg(a){const b=this.sb.get(a);if(!b)throw Error("expected pending tag");b.kd--;0===b.kd&&(b.resolve(),this.sb.delete(a))}Cc(a){a||(a=this.ae);return(a=this.sb.get(a))?a.ah:Promise.resolve()}Jb(){if(0<this.Ha.size)J(this);else for(const a of this.D)if(a.ud()){J(this);break}}wa(){for(var a of this.Ha)a.wa();a=this.rc();for(var b of this.D)b.wa(a);b=this.D.filter(c=>c.ud()).map(c=>c.Ua());x(this,"state",{tickCount:this.be,audioInstances:b,analysers:[...this.Ha].map(c=>
c.Ie())});0===b.length&&0===this.Ha.size&&L(this)}yc(a,b,c){x(this,"trigger",{type:a,tag:b,aiid:c})}async hg(a){const b=a.originalUrl,c=a.url,g=a.type,m=a.isMusic,p=a.tag,u=a.isLooping,A=a.vol,C=a.pos,v=a.panning;let w=a.off;0<w&&!a.trueClock&&(this.c.getOutputTimestamp?(a=this.c.getOutputTimestamp(),w=w-a.performanceTime/1E3+a.contextTime):w=w-performance.now()/1E3+this.c.currentTime);this.ae=p;this.Ze(p);try{this.ia=await this.Fc(b,c,g,p,m),v?(this.ia.Eb(!0),this.ia.Ue(v.x,v.y,v.angle,v.innerAngle,
v.outerAngle,v.outerGain),v.hasOwnProperty("uid")&&this.ia.We(v.uid)):this.ia.Eb(!1),this.ia.Play(u,A,C,w)}catch(D){console.error("[Construct 3] Audio: error starting playback: ",D);return}finally{this.lg(p)}J(this)}Fg(a){a=a.tag;for(const b of this.na(a))b.oa()}Gg(){for(const a of this.D)a.oa()}yg(a){const b=a.tag;a=a.paused;for(const c of this.na(b))a?c.Xa():c.Db();this.Jb()}Dg(a){const b=a.tag;a=a.vol;for(const c of this.na(b))c.Gb(a)}async mf(a){const b=a.tag,c=a.vol,g=a.duration;a=a.stopOnEnd;
await this.Cc(b);for(const m of this.na(b))m.He(c,g,a);this.Jb()}wg(a){this.bd=a.vol;for(const b of this.D)b.Ob()}xg(a){const b=a.tag;a=a.isMuted;for(const c of this.na(b))c.yd(a)}Ag(a){this.qa=a.isSilent;this.u.Fb(this.qa);for(const b of this.D)b.Nb()}vg(a){const b=a.tag;a=a.isLooping;for(const c of this.na(b))c.Ac(a)}async zg(a){const b=a.tag;a=a.rate;await this.Cc(b);for(const c of this.na(b))c.Ad(a)}async og(a){const b=a.tag;a=a.pos;await this.Cc(b);for(const c of this.na(b))c.zc(a)}async ig(a){const b=
a.originalUrl,c=a.url,g=a.type;a=a.isMusic;try{await this.Fc(b,c,g,"",a)}catch(m){console.error("[Construct 3] Audio: error preloading: ",m)}}async Jg(a){if(a=await this.Ib("",a.url,a.type,a.isMusic,!0))a.f(),a=this.ca.indexOf(a),-1!==a&&this.ca.splice(a,1)}Kg(){for(const a of this.ca)a.f();this.ca.length=0}Bg(a){a=a.isSuspended;!a&&this.c.resume&&this.c.resume();for(const b of this.D)b.Bc(a);a&&this.c.suspend&&this.c.suspend()}rf(){return this.c?this.c.state:"suspended"}cg(a){this.lc=a.timeScale;
this.Wc=a.gameTime;this.be=a.tickCount;if(0!==this.hd)for(var b of this.D)b.Ga();(b=a.listenerPos)&&this.c.listener.setPosition(b[0],b[1],b[2]);for(const c of a.instPans){a=c.uid;for(const g of this.D)g.ha===a&&g.zd(c.x,c.y,c.angle)}}async Bd(a){var b=a.type;const c=a.tag;var g=a.params;if("filter"===b)g=new self.te(this,...g);else if("delay"===b)g=new self.re(this,...g);else if("convolution"===b){b=null;try{b=await this.Ib(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(m){console.log("[Construct 3] Audio: error loading convolution: ",
m);return}g=new self.qe(this,b.ba,...g);g.qg(a.bufferOriginalUrl,a.bufferType)}else if("flanger"===b)g=new self.ue(this,...g);else if("phaser"===b)g=new self.we(this,...g);else if("gain"===b)g=new self.ve(this,...g);else if("tremolo"===b)g=new self.ye(this,...g);else if("ringmod"===b)g=new self.xe(this,...g);else if("distortion"===b)g=new self.se(this,...g);else if("compressor"===b)g=new self.pe(this,...g);else if("analyser"===b)g=new self.oe(this,...g);else throw Error("invalid effect type");this.ne(c,
g);this.Md()}sg(a){const b=a.index,c=a.param,g=a.value,m=a.ramp,p=a.time;a=this.da.get(a.tag);!a||0>b||b>=a.length||(a[b].Y(c,g,m,p),this.Md())}kg(a){a=a.tag.toLowerCase();const b=this.da.get(a);if(b&&b.length){for(const c of b)c.f();this.da.delete(a);this.Nd(a)}}Ye(a){this.Ha.add(a);this.Jb()}jg(a){this.Ha.delete(a)}Md(){this.$c||(this.$c=!0,Promise.resolve().then(()=>this.kf()))}kf(){const a={};for(const [b,c]of this.da)a[b]=c.map(g=>g.Ua());x(this,"fxstate",{fxstate:a});this.$c=!1}async Lf(a){const b=
a.saveLoadMode;if(3!==b)for(var c of this.D)c.va()&&1===b||(c.va()||2!==b)&&c.oa();for(const g of this.da.values())for(const m of g)m.f();this.da.clear();this.lc=a.timeScale;this.Wc=a.gameTime;c=a.listenerPos;this.c.listener.setPosition(c[0],c[1],c[2]);this.qa=a.isSilent;this.u.Fb(this.qa);this.bd=a.masterVolume;c=[];for(const g of Object.values(a.effects))c.push(Promise.all(g.map(m=>this.Bd(m))));await Promise.all(c);await Promise.all(a.playing.map(g=>this.vf(g,b)));this.Jb()}async vf(a,b){if(3!==
b){var c=a.bufferOriginalUrl,g=a.bufferUrl,m=a.bufferType,p=a.isMusic,u=a.tag,A=a.isLooping,C=a.volume,v=a.playbackTime;if(!p||1!==b)if(p||2!==b){b=null;try{b=await this.Fc(c,g,m,u,p)}catch(w){console.error("[Construct 3] Audio: error loading audio state: ",w);return}b.Qe(a.pan);b.Play(A,C,v,0);a.isPlaying||b.Xa();b.Jc(a)}}}Nf(a,b){this.Ba&&this.Ba.disconnect();this.cd=b.toLowerCase();this.Ba=this.c.createMediaStreamSource(a);this.Ba.connect(this.td(this.cd))}Gf(){this.Qb||(this.Qb=this.c.createMediaStreamDestination(),
this.Rb.connect(this.Qb));return this.Qb.stream}static Ge(a,b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static Xe(a){return a*e}static Ee(a){return Math.pow(10,a/20)}static rd(a){return Math.max(Math.min(self.fa.Ee(a),1),0)}static Pe(a){return Math.log(a)/Math.log(10)*20}static Oe(a){return self.fa.Pe(Math.max(Math.min(a,1),0))}static Wg(a,b){return 1-Math.exp(-b*a)}};self.Ea.Ta(self.fa)}"use strict";function U(e){e.Xb||(e.Xb=e.Ic());return e.Xb}
self.nd=class{constructor(e,a,b,c,g){this.i=e;this.Rg=a;this.Ca=b;this.R=c;this.Og=g;this.Rc="";this.Xb=null}f(){this.Xb=this.i=null}Ic(){}X(){return this.i.X()}tc(){return this.Rg}Va(){return this.Ca}sc(){return this.R}va(){return this.Og}ga(){}};"use strict";
self.ze=class extends self.nd{constructor(e,a,b,c,g){super(e,a,b,c,g);this.Rc="html5";this.K=new Audio;this.K.crossOrigin="anonymous";this.K.autoplay=!1;this.K.preload="auto";this.mb=this.nb=null;this.K.addEventListener("canplaythrough",()=>!0);this.rb=this.X().createGain();this.pb=null;this.K.addEventListener("canplay",()=>{this.nb&&(this.nb(),this.mb=this.nb=null);!this.pb&&this.K&&(this.pb=this.X().createMediaElementSource(this.K),this.pb.connect(this.rb))});this.onended=null;this.K.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.K.addEventListener("error",m=>{console.error(`[Construct 3] Audio '${this.Ca}' error: `,m);this.mb&&(this.mb(m),this.mb=this.nb=null)})}f(){this.i.xd(this);this.rb.disconnect();this.rb=null;this.pb.disconnect();this.pb=null;this.K&&!this.K.paused&&this.K.pause();this.K=this.onended=null;super.f()}Ic(){return new Promise((e,a)=>{this.nb=e;this.mb=a;this.K.src=this.Ca})}O(){return this.K}ga(){return this.K.duration}};"use strict";
async function V(e){if(e.za)return e.za;var a=e.i.u;if("cordova"===a.A&&a.vd(e.Ca)&&a.jb)e.za=await a.yb(e.Ca);else{a=await fetch(e.Ca);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);e.za=await a.arrayBuffer()}}async function W(e){if(e.ba)return e.ba;e.ba=await e.i.Fe(e.za,e.Qg);e.za=null}
self.Be=class extends self.nd{constructor(e,a,b,c,g,m){super(e,a,b,c,g);this.Rc="webaudio";this.ba=this.za=null;this.Qg=!!m}f(){this.i.xd(this);this.ba=this.za=null;super.f()}async Ic(){try{await V(this),await W(this)}catch(e){console.error(`[Construct 3] Failed to load audio '${this.Ca}': `,e)}}ga(){return this.ba?this.ba.duration:0}};"use strict";
{let e=0;self.od=class{constructor(a,b,c){this.i=a;this.L=b;this.$=c;this.Pb=e++;this.M=this.X().createGain();this.M.connect(this.ua());this.B=null;this.kb=!1;this.la=[0,0,0];this.ka=[0,0,0];this.I=!0;this.W=this.ma=this.H=!1;this.vb=1;this.Ia=!1;this.sa=1;a=this.i.hd;this.ad=1===a&&!this.va()||2===a;this.gb=this.ha=-1;this.ie=!1}f(){this.L=this.i=null;this.B&&(this.B.disconnect(),this.B=null);this.M.disconnect();this.M=null}X(){return this.i.X()}ua(){return this.i.td(this.$)}Bb(){return this.i.Bb()}Ab(){return this.ad?
this.i.Wc:performance.now()/1E3}tc(){return this.L.tc()}Va(){return this.L.Va()}sc(){return this.L.sc()}va(){return this.L.va()}Ve(a){this.$=a}T(){}oc(){}IsPlaying(){return!this.I&&!this.H&&!this.T()}ud(){return!this.I&&!this.T()}Da(){}ga(){return this.L.ga()}Play(){}oa(){}Xa(){}Db(){}Gb(a){this.vb=a;this.M.gain.cancelScheduledValues(0);this.gb=-1;this.M.gain.value=this.uc()}He(a,b,c){if(!this.Ia){a*=this.Bb();var g=this.M.gain;g.cancelScheduledValues(0);var m=this.i.rc();b=m+b;g.setValueAtTime(g.value,
m);g.linearRampToValueAtTime(a,b);this.vb=a;this.gb=b;this.ie=c}}Ob(){this.Gb(this.vb)}wa(a){-1!==this.gb&&a>=this.gb&&(this.gb=-1,this.ie&&this.oa(),this.i.yc("fade-ended",this.$,this.Pb))}uc(){const a=this.vb*this.Bb();return isFinite(a)?a:0}yd(a){a=!!a;this.Ia!==a&&(this.Ia=a,this.Nb())}Cb(){return this.i.Cb()}Nb(){}Ac(){}Ad(a){this.sa!==a&&(this.sa=a,this.Ga())}Ga(){}zc(){}Bc(){}Eb(a){a=!!a;this.kb!==a&&((this.kb=a)?(this.B||(this.B=this.X().createPanner(),this.B.panningModel=this.i.de,this.B.distanceModel=
this.i.Vd,this.B.refDistance=this.i.ee,this.B.maxDistance=this.i.ce,this.B.rolloffFactor=this.i.ge),this.M.disconnect(),this.M.connect(this.B),this.B.connect(this.ua())):(this.B.disconnect(),this.M.disconnect(),this.M.connect(this.ua())))}Ue(a,b,c,g,m,p){this.kb&&(this.zd(a,b,c),a=self.fa.Xe,this.B.coneInnerAngle=a(g),this.B.coneOuterAngle=a(m),this.B.coneOuterGain=p)}zd(a,b,c){this.kb&&(this.la[0]=a,this.la[1]=b,this.la[2]=0,this.ka[0]=Math.cos(c),this.ka[1]=Math.sin(c),this.ka[2]=0,this.B.setPosition(...this.la),
this.B.setOrientation(...this.ka))}We(a){this.ha=a}vc(){}Se(a){const b=this.B||this.M;b.disconnect();b.connect(a)}Ua(){return{aiid:this.Pb,tag:this.$,duration:this.ga(),volume:this.vb,isPlaying:this.IsPlaying(),playbackTime:this.Da(),playbackRate:this.sa,uid:this.ha,bufferOriginalUrl:this.tc(),bufferUrl:"",bufferType:this.sc(),isMusic:this.va(),isLooping:this.W,isMuted:this.Ia,resumePosition:this.vc(),pan:this.Je()}}Jc(a){this.Ad(a.playbackRate);this.yd(a.isMuted)}Je(){if(!this.B)return null;const a=
this.B;return{pos:this.la,orient:this.ka,cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.ha}}Qe(a){if(a){this.Eb(!0);a=this.B;var b=a.pos;this.la[0]=b[0];this.la[1]=b[1];this.la[2]=b[2];b=a.orient;this.ka[0]=b[0];this.ka[1]=b[1];this.ka[2]=b[2];a.setPosition(...this.la);a.setOrientation(...this.ka);a.coneInnerAngle=a.cia;a.coneOuterAngle=a.coa;a.coneOuterGain=a.cog;this.ha=a.uid}else this.Eb(!1)}}}"use strict";
self.Ae=class extends self.od{constructor(e,a,b){super(e,a,b);this.L.rb.connect(this.M);this.L.onended=()=>this.Kc()}f(){this.oa();this.L.rb.disconnect();super.f()}O(){return this.L.O()}Kc(){this.I=!0;this.ha=-1;this.i.yc("ended",this.$,this.Pb)}T(){return this.O().ended}oc(){return this.I?!0:this.T()}Da(){let e=this.O().currentTime;this.W||(e=Math.min(e,this.ga()));return e}Play(e,a,b){const c=this.O();1!==c.playbackRate&&(c.playbackRate=1);c.loop!==e&&(c.loop=e);this.Gb(a);c.muted&&(c.muted=!1);
if(c.currentTime!==b)try{c.currentTime=b}catch(g){console.warn(`[Construct 3] Exception seeking audio '${this.L.Va()}' to position '${b}': `,g)}this.i.Z(c);this.H=this.I=!1;this.W=e;this.sa=1}oa(){const e=this.O();e.paused||e.pause();this.i.aa(e);this.I=!0;this.H=!1;this.ha=-1}Xa(){if(!(this.H||this.I||this.T())){var e=this.O();e.paused||e.pause();this.i.aa(e);this.H=!0}}Db(){!this.H||this.I||this.T()||(this.i.Z(this.O()),this.H=!1)}Nb(){this.O().muted=this.Ia||this.Cb()}Ac(e){e=!!e;this.W!==e&&(this.W=
e,this.O().loop=e)}Ga(){let e=this.sa;this.ad&&(e*=this.i.lc);try{this.O().playbackRate=e}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${e}':`,a)}}zc(e){if(!this.I&&!this.T())try{this.O().currentTime=e}catch(a){console.warn(`[Construct 3] Error seeking audio to '${e}': `,a)}}vc(){return this.Da()}Bc(e){e?this.IsPlaying()?(this.O().pause(),this.ma=!0):this.ma=!1:this.ma&&(this.i.Z(this.O()),this.ma=!1)}};"use strict";function X(e){e.j&&e.j.disconnect();e.j=null;e.ab=null}
self.Ce=class extends self.od{constructor(e,a,b){super(e,a,b);this.j=null;this.ac=c=>this.Kc(c);this.Xc=!0;this.ab=null;this.N=this.bc=this.cc=0;this.dd=1}f(){this.oa();X(this);this.ac=null;super.f()}Kc(e){this.H||this.ma||e.target!==this.ab||(this.I=this.Xc=!0,this.ha=-1,X(this),this.i.yc("ended",this.$,this.Pb))}T(){return!this.I&&this.j&&this.j.loop||this.H?!1:this.Xc}oc(){return!this.j||this.I?!0:this.T()}Da(){let e;e=this.H?this.N:this.bc+(this.Ab()-this.cc)*this.sa;this.W||(e=Math.min(e,this.ga()));
return e}Play(e,a,b,c){this.dd=1;this.Gb(a);X(this);this.j=this.X().createBufferSource();this.j.buffer=this.L.ba;this.j.connect(this.M);this.ab=this.j;this.j.onended=this.ac;this.j.loop=e;this.j.start(c,b);this.H=this.I=this.Xc=!1;this.W=e;this.sa=1;this.cc=this.Ab();this.bc=b}oa(){if(this.j)try{this.j.stop(0)}catch(e){}this.I=!0;this.H=!1;this.ha=-1}Xa(){this.H||this.I||this.T()||(this.N=this.Da(),this.W&&(this.N%=this.ga()),this.H=!0,this.j.stop(0))}Db(){!this.H||this.I||this.T()||(X(this),this.j=
this.X().createBufferSource(),this.j.buffer=this.L.ba,this.j.connect(this.M),this.ab=this.j,this.j.onended=this.ac,this.j.loop=this.W,this.Ob(),this.Ga(),this.j.start(0,this.N),this.cc=this.Ab(),this.bc=this.N,this.H=!1)}uc(){return super.uc()*this.dd}Nb(){this.dd=this.Ia||this.Cb()?0:1;this.Ob()}Ac(e){e=!!e;this.W!==e&&(this.W=e,this.j&&(this.j.loop=e))}Ga(){let e=this.sa;this.ad&&(e*=this.i.lc);this.j&&(this.j.playbackRate.value=e)}zc(e){this.I||this.T()||(this.H?this.N=e:(this.Xa(),this.N=e,this.Db()))}vc(){return this.N}Bc(e){e?
this.IsPlaying()?(this.ma=!0,this.N=this.Da(),this.W&&(this.N%=this.ga()),this.j.stop(0)):this.ma=!1:this.ma&&(X(this),this.j=this.X().createBufferSource(),this.j.buffer=this.L.ba,this.j.connect(this.M),this.ab=this.j,this.j.onended=this.ac,this.j.loop=this.W,this.Ob(),this.Ga(),this.j.start(0,this.N),this.cc=this.Ab(),this.bc=this.N,this.ma=!1)}Jc(e){super.Jc(e);this.N=e.resumePosition}};"use strict";
{class e{constructor(a){this.i=a;this.c=a.X();this.Yd=-1;this.R=this.$="";this.g=null}f(){this.c=null}ug(a){this.Yd=a}Cg(a){this.$=a}o(){return this.c.createGain()}P(){}S(){}m(a,b,c,g){a.cancelScheduledValues(0);if(0===g)a.value=b;else{var m=this.c.currentTime;g+=m;switch(c){case 0:a.setValueAtTime(b,g);break;case 1:a.setValueAtTime(a.value,m);a.linearRampToValueAtTime(b,g);break;case 2:a.setValueAtTime(a.value,m),a.exponentialRampToValueAtTime(b,g)}}}Ua(){return{type:this.R,tag:this.$,params:this.g}}}
self.te=class extends e{constructor(a,b,c,g,m,p,u){super(a);this.R="filter";this.g=[b,c,g,m,p,u];this.l=this.o();this.b=this.o();this.b.gain.value=u;this.a=this.o();this.a.gain.value=1-u;this.v=this.c.createBiquadFilter();this.v.type=b;this.v.frequency.value=c;this.v.detune.value=g;this.v.Q.value=m;this.v.gain.vlaue=p;this.l.connect(this.v);this.l.connect(this.a);this.v.connect(this.b)}f(){this.l.disconnect();this.v.disconnect();this.b.disconnect();this.a.disconnect();super.f()}S(a){this.b.disconnect();
this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}Y(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b,c,g);this.m(this.a.gain,1-b,c,g);break;case 1:this.g[1]=b;this.m(this.v.frequency,b,c,g);break;case 2:this.g[2]=b;this.m(this.v.detune,b,c,g);break;case 3:this.g[3]=b;this.m(this.v.Q,b,c,g);break;case 4:this.g[4]=b,this.m(this.v.gain,b,c,g)}}};self.re=class extends e{constructor(a,b,c,g){super(a);this.R="delay";this.g=[b,c,g];this.l=
this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=1-g;this.ob=this.o();this.U=this.c.createDelay(b);this.U.delayTime.value=b;this.fb=this.o();this.fb.gain.value=c;this.l.connect(this.ob);this.l.connect(this.a);this.ob.connect(this.b);this.ob.connect(this.U);this.U.connect(this.fb);this.fb.connect(this.ob)}f(){this.l.disconnect();this.b.disconnect();this.a.disconnect();this.ob.disconnect();this.U.disconnect();this.fb.disconnect();super.f()}S(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}P(){return this.l}Y(a,b,c,g){const m=self.fa.rd;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[2]=b;this.m(this.b.gain,b,c,g);this.m(this.a.gain,1-b,c,g);break;case 4:this.g[1]=m(b);this.m(this.fb.gain,m(b),c,g);break;case 5:this.g[0]=b,this.m(this.U.delayTime,b,c,g)}}};self.qe=class extends e{constructor(a,b,c,g){super(a);this.R="convolution";this.g=[c,g];this.Td=this.Sd="";this.l=this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=
1-g;this.eb=this.c.createConvolver();this.eb.normalize=c;this.eb.buffer=b;this.l.connect(this.eb);this.l.connect(this.a);this.eb.connect(this.b)}f(){this.l.disconnect();this.eb.disconnect();this.b.disconnect();this.a.disconnect();super.f()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}Y(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[1]=b,this.m(this.b.gain,b,c,g),this.m(this.a.gain,1-b,c,g)}}qg(a,b){this.Sd=a;this.Td=b}Ua(){const a=
super.Ua();a.bufferOriginalUrl=this.Sd;a.bufferUrl="";a.bufferType=this.Td;return a}};self.ue=class extends e{constructor(a,b,c,g,m,p){super(a);this.R="flanger";this.g=[b,c,g,m,p];this.l=this.o();this.a=this.o();this.a.gain.value=1-p/2;this.b=this.o();this.b.gain.value=p/2;this.hb=this.o();this.hb.gain.value=m;this.U=this.c.createDelay(b+c);this.U.delayTime.value=b;this.s=this.c.createOscillator();this.s.frequency.value=g;this.J=this.o();this.J.gain.value=c;this.l.connect(this.U);this.l.connect(this.a);
this.U.connect(this.b);this.U.connect(this.hb);this.hb.connect(this.U);this.s.connect(this.J);this.J.connect(this.U.delayTime);this.s.start(0)}f(){this.s.stop(0);this.l.disconnect();this.U.disconnect();this.s.disconnect();this.J.disconnect();this.a.disconnect();this.b.disconnect();this.hb.disconnect();super.f()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}Y(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[4]=b;this.m(this.b.gain,
b/2,c,g);this.m(this.a.gain,1-b/2,c,g);break;case 6:this.g[1]=b/1E3;this.m(this.J.gain,b/1E3,c,g);break;case 7:this.g[2]=b;this.m(this.s.frequency,b,c,g);break;case 8:this.g[3]=b/100,this.m(this.hb.gain,b/100,c,g)}}};self.we=class extends e{constructor(a,b,c,g,m,p,u){super(a);this.R="phaser";this.g=[b,c,g,m,p,u];this.l=this.o();this.a=this.o();this.a.gain.value=1-u/2;this.b=this.o();this.b.gain.value=u/2;this.v=this.c.createBiquadFilter();this.v.type="allpass";this.v.frequency.value=b;this.v.detune.value=
c;this.v.Q.value=g;this.s=this.c.createOscillator();this.s.frequency.value=p;this.J=this.o();this.J.gain.value=m;this.l.connect(this.v);this.l.connect(this.a);this.v.connect(this.b);this.s.connect(this.J);this.J.connect(this.v.frequency);this.s.start(0)}f(){this.s.stop(0);this.l.disconnect();this.v.disconnect();this.s.disconnect();this.J.disconnect();this.a.disconnect();this.b.disconnect();super.f()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}Y(a,
b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b/2,c,g);this.m(this.a.gain,1-b/2,c,g);break;case 1:this.g[0]=b;this.m(this.v.frequency,b,c,g);break;case 2:this.g[1]=b;this.m(this.v.detune,b,c,g);break;case 3:this.g[2]=b;this.m(this.v.Q,b,c,g);break;case 6:this.g[3]=b;this.m(this.J.gain,b,c,g);break;case 7:this.g[4]=b,this.m(this.s.frequency,b,c,g)}}};self.ve=class extends e{constructor(a,b){super(a);this.R="gain";this.g=[b];this.h=this.o();this.h.gain.value=
b}f(){this.h.disconnect();super.f()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}Y(a,b,c,g){const m=self.fa.rd;switch(a){case 4:this.g[0]=m(b),this.m(this.h.gain,m(b),c,g)}}};self.ye=class extends e{constructor(a,b,c){super(a);this.R="tremolo";this.g=[b,c];this.h=this.o();this.h.gain.value=1-c/2;this.s=this.c.createOscillator();this.s.frequency.value=b;this.J=this.o();this.J.gain.value=c/2;this.s.connect(this.J);this.J.connect(this.h.gain);this.s.start(0)}f(){this.s.stop(0);this.s.disconnect();
this.J.disconnect();this.h.disconnect();super.f()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}Y(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.h.gain,1-b/2,c,g);this.m(this.J.gain,b/2,c,g);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,c,g)}}};self.xe=class extends e{constructor(a,b,c){super(a);this.R="ringmod";this.g=[b,c];this.l=this.o();this.b=this.o();this.b.gain.value=c;this.a=this.o();this.a.gain.value=1-c;this.ub=this.o();this.ub.gain.value=
0;this.s=this.c.createOscillator();this.s.frequency.value=b;this.s.connect(this.ub.gain);this.s.start(0);this.l.connect(this.ub);this.l.connect(this.a);this.ub.connect(this.b)}f(){this.s.stop(0);this.s.disconnect();this.ub.disconnect();this.l.disconnect();this.b.disconnect();this.a.disconnect();super.f()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}Y(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.b.gain,b,c,g);
this.m(this.a.gain,1-b,c,g);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,c,g)}}};self.se=class extends e{constructor(a,b,c,g,m,p){super(a);this.R="distortion";this.g=[b,c,g,m,p];this.l=this.o();this.hc=this.o();this.fc=this.o();this.rg(g,m);this.b=this.o();this.b.gain.value=p;this.a=this.o();this.a.gain.value=1-p;this.mc=this.c.createWaveShaper();this.Tc=new Float32Array(65536);this.pf(b,c);this.mc.curve=this.Tc;this.l.connect(this.hc);this.l.connect(this.a);this.hc.connect(this.mc);this.mc.connect(this.fc);
this.fc.connect(this.b)}f(){this.l.disconnect();this.hc.disconnect();this.mc.disconnect();this.fc.disconnect();this.b.disconnect();this.a.disconnect();super.f()}rg(a,b){.01>a&&(a=.01);this.hc.gain.value=a;this.fc.gain.value=Math.pow(1/a,.6)*b}pf(a,b){for(let c=0;32768>c;++c){let g=c/32768;g=this.Eg(g,a,b);this.Tc[32768+c]=g;this.Tc[32768-c-1]=-g}}Eg(a,b,c){c=1.05*c*b-b;const g=0>a?-a:a;return(g<b?g:b+c*self.fa.Wg(g-b,1/c))*(0>a?-1:1)}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();
this.a.connect(a)}P(){return this.l}Y(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[4]=b,this.m(this.b.gain,b,c,g),this.m(this.a.gain,1-b,c,g)}}};self.pe=class extends e{constructor(a,b,c,g,m,p){super(a);this.R="compressor";this.g=[b,c,g,m,p];this.h=this.c.createDynamicsCompressor();this.h.threshold.value=b;this.h.knee.value=c;this.h.ratio.value=g;this.h.attack.value=m;this.h.release.value=p}f(){this.h.disconnect();super.f()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}Y(){}};
self.oe=class extends e{constructor(a,b,c){super(a);this.R="analyser";this.g=[b,c];this.h=this.c.createAnalyser();this.h.fftSize=b;this.h.smoothingTimeConstant=c;this.Wd=new Float32Array(this.h.frequencyBinCount);this.he=new Uint8Array(b);this.fe=this.Ma=0;this.i.Ye(this)}f(){this.i.jg(this);this.h.disconnect();super.f()}wa(){this.h.getFloatFrequencyData(this.Wd);this.h.getByteTimeDomainData(this.he);const a=this.h.fftSize;let b=this.Ma=0;for(var c=0;c<a;++c){let g=(this.he[c]-128)/128;0>g&&(g=-g);
this.Ma<g&&(this.Ma=g);b+=g*g}c=self.fa.Oe;this.Ma=c(this.Ma);this.fe=c(Math.sqrt(b/a))}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}Y(){}Ie(){return{tag:this.$,index:this.Yd,peak:this.Ma,rms:this.fe,binCount:this.h.frequencyBinCount,freqBins:this.Wd}}}}"use strict";
self.Ea.Ta(class extends self.zb{constructor(e){super(e,"mouse");I(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.u.G.requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{x(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{x(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
"use strict";
self.Ea.Ta(class extends self.qd{constructor(e){super(e,"video");this.kc=this.Vb=this.bb=!1;this.$b=this.Tg=0;this.Uc=new WeakSet;E(this,"init",a=>this.Jf(a));Q(this,"play",a=>this.Qf(a));Q(this,"pause",a=>this.Pf(a));Q(this,"set-source",(a,b)=>this.$f(a,b));Q(this,"set-playback-time",(a,b)=>this.Zf(a,b));Q(this,"set-looping",(a,b)=>this.Xf(a,b));Q(this,"set-muted",(a,b)=>this.Yf(a,b));Q(this,"set-volume",(a,b)=>this.bg(a,b));self.C3Video_GetElement=a=>this.V.get(a)}async Jf(e){this.Vb=e.isInWorker;
e=document.createElement("video");this.kc=!!e.requestVideoFrameCallback;return{"video/webm":!!e.canPlayType("video/webm"),"video/ogg":!!e.canPlayType("video/ogg"),"video/mp4":!!e.canPlayType("video/mp4")}}Z(e){this.u.Z(e);this.Vb&&this.kc&&-1===e.c3_rvfcId&&(e.c3_rvfcId=e.requestVideoFrameCallback(()=>this.Ld(e)))}aa(e){this.u.aa(e);this.Vb&&this.kc&&-1!==e.c3_rvfcId&&(e.cancelVideoFrameCallback(e.c3_rvfcId),e.c3_rvfcId=-1)}async Ld(e){if(!this.Uc.has(e)){e.c3_rvfcId=e.requestVideoFrameCallback(()=>
this.Ld(e));try{const a=e.c3_sequenceNumber++,b=await createImageBitmap(e);a>e.c3_lastFrameSequence&&(e.c3_imageBitmap=b,e.c3_lastFrameSequence=a)}catch(a){}}}pc(e,a){const b=document.createElement("video");b.crossOrigin="anonymous";b.playsInline=!0;b.c3_imageBitmap=null;b.c3_rvfcId=-1;b.c3_sequenceNumber=0;b.c3_lastFrameSequence=-1;b.addEventListener("canplay",()=>this.pa(b,e,0));b.addEventListener("canplaythrough",()=>this.pa(b,e,1));b.addEventListener("ended",()=>this.pa(b,e,2));b.addEventListener("error",
()=>this.pa(b,e,3));b.addEventListener("loadstart",()=>this.pa(b,e,4));b.addEventListener("playing",()=>this.pa(b,e,5));b.addEventListener("pause",()=>this.pa(b,e,6));b.addEventListener("stalled",()=>this.pa(b,e,7));const c=a.autoplay;0===c?(b.autoplay=!1,b.preload="none"):1===c?(b.autoplay=!1,b.preload="auto"):b.autoplay=!0;a.src&&(b.src=a.src);2===c&&this.Z(b);this.$b++;J(this);return b}pa(e,a,b){this.Uc.has(e)||P(this,"playback-event",a,{type:b})}Hb(){}sd(e){this.aa(e);e&&!e.paused&&!e.ended&&
0<e.currentTime&&e.pause();e.src="";this.$b=Math.max(this.$b-1,0);0===this.$b&&L(this);this.Uc.add(e)}Qf(e){this.Z(e)}Pf(e){this.aa(e);e.pause()}$f(e,a){e.src=a.src;e.load()}Zf(e,a){try{e.currentTime=a.time}catch(b){console.error("[Video] Exception setting playback time: ",b)}}Xf(e,a){e.loop=a.isLooping}Yf(e,a){e.muted=a.isMuted}bg(e,a){e.volume=a.volume}wa(){const e={},a={sequenceNumber:this.Tg++,videoData:e},b=[],c=[];for(const [g,m]of this.V.entries()){const p={currentTime:m.currentTime,duration:m.duration,
videoWidth:m.videoWidth,videoHeight:m.videoHeight};if(this.Vb)if(this.kc){const u=m.c3_imageBitmap;m.c3_imageBitmap=null;(p.imageBitmap=u)&&b.push(u)}else c.push(createImageBitmap(m).then(u=>{p.imageBitmap=u;b.push(u)}).catch(()=>{p.imageBitmap=null}));e[g.toString()]=p}Promise.all(c).then(()=>x(this,"state",a,!1,b))}});"use strict";
{function e(a){a.stopPropagation()}self.Ea.Ta(class extends self.qd{constructor(a){super(a,"progress-bar")}pc(a,b){const c=document.createElement("progress");c.style.position="absolute";c.style.userSelect="none";c.style.webkitUserSelect="none";c.addEventListener("touchstart",e);c.addEventListener("touchmove",e);c.addEventListener("touchend",e);c.addEventListener("mousedown",e);c.addEventListener("mouseup",e);c.addEventListener("click",()=>{var g;g||(g={});g.elementId=a;B(this,"click",g)});b.id&&(c.id=
b.id);this.Hb(c,b);return c}Hb(a,b){a.title=b.title;const c=b.value;b=b.max;0<b&&0<=c?(a.max=b,a.value=c):(a.removeAttribute("value"),a.removeAttribute("max"))}})};
